{
  "uid" : "5c23f0a6e70ec172",
  "name" : "TestCheckInit.test_self",
  "title" : "Test self",
  "time" : {
    "start" : 1525901683708,
    "stop" : 1525901683710,
    "duration" : 2
  },
  "summary" : {
    "attachments" : 1,
    "steps" : 0
  },
  "failure" : null,
  "description" : null,
  "severity" : "NORMAL",
  "status" : "PASSED",
  "testId" : null,
  "suite" : {
    "uid" : "6d45831bf6a3d4ff",
    "name" : "test_first",
    "title" : "Test first"
  },
  "steps" : [ ],
  "attachments" : [ {
    "title" : "Captured stdout call",
    "source" : "e8208fce-4f11-4c1f-8d6c-d629bef85bfa-attachment.txt",
    "type" : "text/plain",
    "size" : 4,
    "uid" : "eb8afe77e509b10c"
  } ],
  "issues" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Incorrect input"
  }, {
    "name" : "suite-name",
    "value" : "test_first"
  }, {
    "name" : "story",
    "value" : "Checking the output with param as self 'check_init' function"
  }, {
    "name" : "thread",
    "value" : "7087-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "suite-title",
    "value" : null
  }, {
    "name" : "host",
    "value" : "familypc"
  }, {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "language",
    "value" : "cpython2"
  } ],
  "parameters" : [ ]
}