{
  "uid" : "caafd43e26d29222",
  "name" : "TestCheckInit.test_two_arg_in_func",
  "title" : "Test two arg in func",
  "time" : {
    "start" : 1525886391572,
    "stop" : 1525886391589,
    "duration" : 17
  },
  "summary" : {
    "attachments" : 1,
    "steps" : 0
  },
  "failure" : {
    "message" : "TypeError: check_ident() takes exactly 1 argument (2 given)",
    "stackTrace" : "self = <test_first.TestCheckInit instance at 0x7fb2d9bff9e0>\n\n    def test_two_arg_in_func(self):\n>       result = Check.check_ident(\"9876543219 9\",\"9876543219 9\")\nE       TypeError: check_ident() takes exactly 1 argument (2 given)\n\ntest_first.py:25: TypeError"
  },
  "description" : null,
  "severity" : "NORMAL",
  "status" : "FAILED",
  "testId" : null,
  "suite" : {
    "uid" : "be762428afaeecb9",
    "name" : "test_first",
    "title" : "Test first"
  },
  "steps" : [ ],
  "attachments" : [ {
    "title" : "Captured stdout setup",
    "source" : "b7810f24-379c-472f-939f-6b18f68b808f-attachment.txt",
    "type" : "text/plain",
    "size" : 6,
    "uid" : "8331be1728917da1"
  } ],
  "issues" : [ ],
  "labels" : [ {
    "name" : "suite-name",
    "value" : "test_first"
  }, {
    "name" : "thread",
    "value" : "10143-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "suite-title",
    "value" : null
  }, {
    "name" : "host",
    "value" : "familypc"
  }, {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "language",
    "value" : "cpython2"
  } ],
  "parameters" : [ ]
}